defaults:
  image:
    # We'll deploy the "composition" example
    repository: ghcr.io/wiremind/remoulade
    tag: docker-example-composition
    pullPolicy: Always
    pullSecrets: []
  labels: {}
  podLabels: {}

  additionalEnvironmentVariables: {foo: a, bar: b}
  terminationGracePeriodSeconds:
  # disableMetrics: true  # By default, metrics are enabled, you can explicitely disable them
  podAnnotations: {}
  priorityClassName:

workers:
  list:
    my-worker-type:
      # Mandatory values to be stated for all types of workers
      replicaCount: 1
      autoscaling:
        enabled: false
      # Optional values, if not defined, will not be used
      command: ["python"]
      args: ["example.py"]
