workers:
  list:
    my-worker-type:
      # Mandatory values to be stated for all types of workers
      replicaCount: 1
      autoscaling:
        enabled: true
        # minReplicas SHOULD be >= 1 for now.
        minReplicas: 1
        maxReplicas: 1
        describedService: "some_service"
        metricName: "some_rabbitmq_queue_name"
        metricMatchLabels:
          queue: queue_name
        targetMetricValue: 42
      # Optional values, if not defined, will use defaults defined earlier
      image:
        # We'll deploy the "composition" example
        repository: ghcr.io/wiremind/remoulade
        tag: docker-example-composition
        pullPolicy: Always
        pullSecrets: []
      labels: {}
      podLabels: {}
      # Optional values, if not defined, will not be used
      command: ["remoulade"]
      args: ["example"]
      additionalEnvironmentVariables: {foo: a, bar: b}
      terminationGracePeriodSeconds:
      # disableMetrics: true  # By default, metrics are enabled, you can explicitely disable them
      podAnnotations: {}
      priorityClassName:

      expectedDeploymentScalePriority: 0  # XXX
      usePrivilegedWiremindConf: false  # XXX (default value is false, if true, uses wiremind conf with privileged postgresql user)

superbowl:
  frontend:
    image:
      tag: master
      pullPolicy: Always
  backend:
    image:
      repository: ghcr.io/wiremind/remoulade
      tag: docker-example-composition
      pullPolicy: Always
    command: [python]
    args: [example.py, --server]
  podAnnotations:
    foo: bar