apiVersion: v1
kind: Secret
metadata:
  name: {{ template "remoulade.fullname" . }}
  labels:
{{ include "remoulade.labels" . | indent 4 }}
type: Opaque
data:
  REMOULADE_POSTGRESQL_URL: {{ printf "postgresql://%s:%s@%s.%s:5432/%s?sslmode=prefer" (index .Values "remoulade-postgresql").postgresqlUsername (index .Values "remoulade-postgresql").postgresqlPassword (include "remoulade.postgresql-host" .) .Release.Namespace (index .Values "remoulade-postgresql").postgresqlDatabase | b64enc }}
  REMOULADE_RABBITMQ_URL: {{ printf "amqp://%s:%s@%s.%s:5672" (index .Values "remoulade-rabbitmq").auth.username (index .Values "remoulade-rabbitmq").auth.password (include "remoulade.rabbitmq-host" .) .Release.Namespace | b64enc }}
  REMOULADE_REDIS_URL: {{ printf "redis://:%s@%s.%s:6379?socket_keepalive=1" (index .Values "remoulade-redis").auth.password (include "remoulade.redis-host" .) .Release.Namespace | b64enc }}
